name: EXPRTS
channels:
  - defaults
dependencies:
  - python=3.9.21
  - pip
  - pip:
    - black
    - bokeh==2.3.3
    - gluonts[torch]==0.12.5
    - jupyterlab==3.1.7
    - matplotlib==3.7.5
    - numpy==1.20.3
    - pandas==1.2.1
    - torch==2.6.0
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - statsmodels==0.12.2
    - tqdm==4.62.1
